name: CI/CD Pipeline for Railway

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Set up Google Cloud service account credentials
      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > service-account-file.json
          # Ensure service-account-file.json is used in the Docker build

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg GOOGLE_APPLICATION_CREDENTIALS=service-account-file.json -t ravijar/petstore .

      # Step 5: Push Docker image to GitHub Container Registry (optional)
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag ravijar/petstore ghcr.io/ravijar/petstore:latest
          docker push ghcr.io/ravijar/petstore:latest

      # Step 6: Trigger Railway Deployment (Optional, this assumes Railway handles the deploy automatically)
      - name: Trigger Railway Deployment
        run: |
          echo "Docker image is ready and pushed to the registry. Triggering Railway deployment..."
          # No need to add railway commands here since Railway will handle deployment.
          # But, if you are using Railway CLI, this can be triggered by:
          # railway deploy
